require("snacks").setup({
	animate = { enabled = false },
	bigfile = { enabled = true },
	bufdelete = { enabled = false },
	dashboard = { enabled = false },
	debug = { enabled = false },
	dim = { enabled = false },
	explorer = { enabled = true },
	git = { enabled = true },
	gitbrowse = { enabled = false },
	image = { enabled = false },
	indent = { enabled = true },
	input = { enabled = true },
	layout = { enabled = false },
	lazygit = { enabled = false },
	notifier = { enabled = true, timeout = 3000, },
	notify = { enalbed = true },
	picker = { enabled = true },
	profiler = { enabled = false },
	quickfile = { enabled = true },
	rename = { enabled = false },
	scope = { enabled = false },
	scratch = { enabled = false },
	scroll = { enabled = false },
	statuscolumn = { enabled = true },
	terminal = { enabled = true },
	toggle = { enable = false },
	win = { enabled = false },
	words = { enabled = true },
	zen = { enabled = false },
})
